<a href="https://colab.research.google.com/github/Damntoochill/Internship/blob/master/RUL_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import files
files.upload()

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

##Read Train and Test Data

In [0]:
# read training data 
train_df = pd.read_csv('PM_train.txt', sep=" ", header=None)
train_df.drop(train_df.columns[[26, 27]], axis=1, inplace=True)
train_df.columns = ['id', 'cycle', 'setting1', 'setting2', 'setting3', 's1', 's2', 's3',
                     's4', 's5', 's6', 's7', 's8', 's9', 's10', 's11', 's12', 's13', 's14',
                     's15', 's16', 's17', 's18', 's19', 's20', 's21']

In [0]:
# read test data 
test_df = pd.read_csv('PM_test.txt', sep=" ", header=None)
test_df.drop(test_df.columns[[26,27]], axis=1, inplace=True)
test_df.columns = ['id', 'cycle', 'setting1', 'setting2', 'setting3', 's1', 's2', 's3',
                     's4', 's5', 's6', 's7', 's8', 's9', 's10', 's11', 's12', 's13', 's14',
                     's15', 's16', 's17', 's18', 's19', 's20', 's21']

In [0]:
# read ground truth data
truth_df = pd.read_csv('PM_truth.txt', sep=" ", header=None)
truth_df.drop(truth_df.columns[[1]], axis=1, inplace=True)

In [21]:
train_df = train_df.sort_values(['id','cycle'])
train_df.head()

id  cycle  setting1  setting2  setting3  ...  s17   s18    s19    s20      s21
0   1      1   -0.0007   -0.0004     100.0  ...  392  2388  100.0  39.06  23.4190
1   1      2    0.0019   -0.0003     100.0  ...  392  2388  100.0  39.00  23.4236
2   1      3   -0.0043    0.0003     100.0  ...  390  2388  100.0  38.95  23.3442
3   1      4    0.0007    0.0000     100.0  ...  392  2388  100.0  38.88  23.3739
4   1      5   -0.0019   -0.0002     100.0  ...  393  2388  100.0  38.90  23.4044

[5 rows x 26 columns]

##Generate Labels for Train Data

In [22]:
# Data Labeling - generate column RUL
rul = pd.DataFrame(train_df.groupby('id')['cycle'].max()).reset_index()
rul.columns = ['id', 'max']
train_df = train_df.merge(rul, on=['id'], how='left')
train_df['RUL'] = train_df['max'] - train_df['cycle']
train_df.drop('max', axis=1, inplace=True)
train_df.head()

id  cycle  setting1  setting2  setting3  ...   s18    s19    s20      s21  RUL
0   1      1   -0.0007   -0.0004     100.0  ...  2388  100.0  39.06  23.4190  191
1   1      2    0.0019   -0.0003     100.0  ...  2388  100.0  39.00  23.4236  190
2   1      3   -0.0043    0.0003     100.0  ...  2388  100.0  38.95  23.3442  189
3   1      4    0.0007    0.0000     100.0  ...  2388  100.0  38.88  23.3739  188
4   1      5   -0.0019   -0.0002     100.0  ...  2388  100.0  38.90  23.4044  187

[5 rows x 27 columns]

In [23]:
# generate label columns for training data
w1 = 30
w0 = 15
train_df['label1'] = np.where(train_df['RUL'] <= w1, 1, 0 )
train_df['label2'] = train_df['label1']
train_df.loc[train_df['RUL'] <= w0, 'label2'] = 2
train_df.head()

id  cycle  setting1  setting2  setting3  ...    s20      s21  RUL  label1  label2
0   1      1   -0.0007   -0.0004     100.0  ...  39.06  23.4190  191       0       0
1   1      2    0.0019   -0.0003     100.0  ...  39.00  23.4236  190       0       0
2   1      3   -0.0043    0.0003     100.0  ...  38.95  23.3442  189       0       0
3   1      4    0.0007    0.0000     100.0  ...  38.88  23.3739  188       0       0
4   1      5   -0.0019   -0.0002     100.0  ...  38.90  23.4044  187       0       0

[5 rows x 29 columns]

##Normalize Train and Test Data

In [25]:
# MinMax normalization
train_df['cycle_norm'] = train_df['cycle']
cols_normalize = train_df.columns.difference(['id','cycle','RUL','label1','label2'])
min_max_scaler = MinMaxScaler()
norm_train_df = pd.DataFrame(min_max_scaler.fit_transform(train_df[cols_normalize]), 
                             columns=cols_normalize, 
                             index=train_df.index)
join_df = train_df[train_df.columns.difference(cols_normalize)].join(norm_train_df)
train_df = join_df.reindex(columns = train_df.columns)
train_df.head()

id  cycle  setting1  setting2  ...  RUL  label1  label2  cycle_norm
0   1      1  0.459770  0.166667  ...  191       0       0     0.00000
1   1      2  0.609195  0.250000  ...  190       0       0     0.00277
2   1      3  0.252874  0.750000  ...  189       0       0     0.00554
3   1      4  0.540230  0.500000  ...  188       0       0     0.00831
4   1      5  0.390805  0.333333  ...  187       0       0     0.01108

[5 rows x 30 columns]

In [35]:
test_df['cycle_norm'] = test_df['cycle']
norm_test_df = pd.DataFrame(min_max_scaler.transform(test_df[cols_normalize]), 
                            columns=cols_normalize, 
                            index=test_df.index)
test_join_df = test_df[test_df.columns.difference(cols_normalize)].join(norm_test_df)
test_df = test_join_df.reindex(columns = test_df.columns)
test_df = test_df.reset_index(drop=True)
test_df.head()

id  cycle  setting1  setting2  ...  RUL  label1  label2  cycle_norm
0   1      1  0.632184  0.750000  ...  142       0       0     0.00000
1   1      2  0.344828  0.250000  ...  141       0       0     0.00277
2   1      3  0.517241  0.583333  ...  140       0       0     0.00554
3   1      4  0.741379  0.500000  ...  139       0       0     0.00831
4   1      5  0.580460  0.500000  ...  138       0       0     0.01108

[5 rows x 30 columns]

##Generate Labels for Test Data

In [0]:
# generate column max for test data
rul = pd.DataFrame(test_df.groupby('id')['cycle'].max()).reset_index()
rul.columns = ['id', 'max']
truth_df.columns = ['more']
truth_df['id'] = truth_df.index + 1
truth_df['max'] = rul['max'] + truth_df['more']
truth_df.drop('more', axis=1, inplace=True)

In [27]:
# generate RUL for test data
test_df = test_df.merge(truth_df, on=['id'], how='left')
test_df['RUL'] = test_df['max'] - test_df['cycle']
test_df.drop('max', axis=1, inplace=True)
test_df.head()

id  cycle  setting1  setting2  setting3  ...   s18    s19    s20      s21  RUL
0   1      1    0.0023    0.0003     100.0  ...  2388  100.0  38.86  23.3735  142
1   1      2   -0.0027   -0.0003     100.0  ...  2388  100.0  39.02  23.3916  141
2   1      3    0.0003    0.0001     100.0  ...  2388  100.0  39.08  23.4166  140
3   1      4    0.0042    0.0000     100.0  ...  2388  100.0  39.00  23.3737  139
4   1      5    0.0014    0.0000     100.0  ...  2388  100.0  38.99  23.4130  138

[5 rows x 27 columns]

In [28]:
# generate label columns w0 and w1 for test data
test_df['label1'] = np.where(test_df['RUL'] <= w1, 1, 0 )
test_df['label2'] = test_df['label1']
test_df.loc[test_df['RUL'] <= w0, 'label2'] = 2
test_df.head()

id  cycle  setting1  setting2  setting3  ...    s20      s21  RUL  label1  label2
0   1      1    0.0023    0.0003     100.0  ...  38.86  23.3735  142       0       0
1   1      2   -0.0027   -0.0003     100.0  ...  39.02  23.3916  141       0       0
2   1      3    0.0003    0.0001     100.0  ...  39.08  23.4166  140       0       0
3   1      4    0.0042    0.0000     100.0  ...  39.00  23.3737  139       0       0
4   1      5    0.0014    0.0000     100.0  ...  38.99  23.4130  138       0       0

[5 rows x 29 columns]

##Choose Columns to be Used for Training

In [0]:
# pick the feature columns 
sensor_cols = ['s' + str(i) for i in range(1,22)]
cols = ['setting1', 'setting2', 'setting3','cycle_norm']
cols.extend(sensor_cols)

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

X_train, X_val, Y_train, Y_val = train_test_split(train_df[cols], train_df['label1'], test_size=0.05, 
                                                  shuffle=False, random_state=42)

print ("Train_shape: " + str(X_train.shape))
print ("Val_shape: " + str(X_val.shape))
print ("No of positives in train: " + str(Y_train.sum()))
print ("No of positives in val: " + str(Y_val.sum()))

Train_shape: (19599, 25)
Val_shape: (1032, 25)
No of positives in train: 2945
No of positives in val: 155


# SVM Classifier

In [31]:
from sklearn.metrics import accuracy_score
print('Start training...')

clf = SVC(C=4.0, kernel='rbf', degree=3, gamma='auto', shrinking=True, verbose=True, max_iter=-1, 
          random_state=42)
clf.fit(X_train, Y_train)
print ("Validation Accuracy: "+str(accuracy_score(Y_val, clf.predict(X_val))))

Start training...
[LibSVM]Validation Accuracy: 0.9612403100775194


## Results on Training set

In [32]:
# training metrics
pred_train = clf.predict(train_df[cols])
pred_train = np.where(pred_train > 0.5, 1, 0)
print('Accurracy: {}'.format(accuracy_score(train_df['label1'], pred_train)))

Accurracy: 0.961611167660317


In [33]:
from sklearn.metrics import confusion_matrix, recall_score, precision_score

print('Confusion matrix\n- x-axis is true labels.\n- y-axis is predicted labels')
cm = confusion_matrix(train_df['label1'], pred_train)
cm

Confusion matrix
- x-axis is true labels.
- y-axis is predicted labels


array([[17247,   284],
       [  508,  2592]])

##Results on Test Set

In [36]:
pred_test = clf.predict(test_df[cols])
pred_test = np.where(pred_test > 0.5, 1, 0)
print('Accurracy: {}'.format(accuracy_score(test_df['label1'], pred_test)))

Accurracy: 0.9860262675626146


In [37]:
print('Confusion matrix\n- x-axis is true labels.\n- y-axis is predicted labels')
cm = confusion_matrix(test_df['label1'], pred_test)
cm

Confusion matrix
- x-axis is true labels.
- y-axis is predicted labels


array([[12722,    42],
       [  141,   191]])

In [38]:
# compute precision and recall
precision_test = precision_score(test_df['label1'], pred_test)
recall_test = recall_score(test_df['label1'], pred_test)
f1_test = 2 * (precision_test * recall_test) / (precision_test + recall_test)
print( 'Precision: ', precision_test, '\n', 'Recall: ', recall_test,'\n', 'F1-score:', f1_test )

Precision:  0.8197424892703863 
 Recall:  0.5753012048192772 
 F1-score: 0.6761061946902656


In [39]:
label_array_test_last = test_df.groupby('id')['label1'].nth(-1).values
label_array_test_last = label_array_test_last.reshape(label_array_test_last.shape[0],1).astype(np.float32)
label_array_test_last.shape

(100, 1)

In [40]:
seq_array_test_last = [test_df[test_df['id']==id][cols].values[-1] for id in test_df['id'].unique()]

seq_array_test_last = np.asarray(seq_array_test_last).astype(np.float32)
seq_array_test_last.shape

(100, 25)

In [41]:
pred_test_last = clf.predict(seq_array_test_last)
pred_test_last = np.where(pred_test_last > 0.5, 1, 0)
acc = accuracy_score(label_array_test_last, pred_test_last)
print('Accurracy: {}'.format(acc))

Accurracy: 0.93


In [42]:
# make predictions and compute confusion matrix
print('Confusion matrix\n- x-axis is true labels.\n- y-axis is predicted labels')
cm = confusion_matrix(label_array_test_last, pred_test_last)
cm

Confusion matrix
- x-axis is true labels.
- y-axis is predicted labels


array([[75,  0],
       [ 7, 18]])

In [43]:
# compute precision and recall
precision_test = precision_score(label_array_test_last, pred_test_last)
recall_test = recall_score(label_array_test_last, pred_test_last)
f1_test = 2 * (precision_test * recall_test) / (precision_test + recall_test)
print( 'Precision: ', precision_test, '\n', 'Recall: ', recall_test,'\n', 'F1-score:', f1_test )

Precision:  1.0 
 Recall:  0.72 
 F1-score: 0.8372093023255813


In [44]:
results_df = pd.DataFrame([[acc,precision_test,recall_test,f1_test],
                          ],
                         columns = ['Accuracy', 'Precision', 'Recall', 'F1-score'],
                         index = ['SVM'])
results_df

Accuracy  Precision  Recall  F1-score
SVM      0.93        1.0    0.72  0.837209

#XGBoost

In [48]:
import xgboost as xgb

params = {}
params['booster'] = 'gbtree'
params['objective'] = 'binary:logistic'
params['eta'] = 0.006
params['eval_metric'] = 'auc'
params['max_depth'] = 4
params['colsample_bytree'] = 0.6
params['subsample'] = 0.5
params['silent'] = 1

d_train = xgb.DMatrix(X_train, label=Y_train)
d_valid = xgb.DMatrix(X_val, label=Y_val)
watchlist = [(d_train, 'train'), (d_valid, 'valid')]

gbm = xgb.train(params, d_train, 2000, watchlist, early_stopping_rounds=50, verbose_eval=25)

/usr/local/lib/python3.6/dist-packages/xgboost/core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[0]	train-auc:0.961598	valid-auc:0.952139
Multiple eval metrics have been passed: 'valid-auc' will be used for early stopping.

Will train until valid-auc hasn't improved in 50 rounds.
[25]	train-auc:0.989747	valid-auc:0.988642
[50]	train-auc:0.990066	valid-auc:0.988906
[75]	train-auc:0.990242	valid-auc:0.988973
[100]	train-auc:0.990404	valid-auc:0.988995
[125]	train-auc:0.990526	valid-auc:0.989267
[150]	train-auc:0.990698	valid-auc:0.989333
[175]	train-auc:0.990796	valid-auc:0.989363
[200]	train-auc:0.990896	valid-auc:0.989458
[225]	train-auc:0.991072	valid-auc:0.989657
[250]	train-auc:0.991201	valid-auc:0.989679
[275]	train-auc:0.991338	valid-auc:0.989797
[300]	train-auc:0.991443	valid-auc:0.989848
[325]	train-auc:0.991571	valid-auc:0.990017
[350]	train-auc:0.99171	valid-auc:0.990179
[375]	train-auc:0.99182	valid-auc:0.990304
[400]	train-auc:0.991979	valid-auc:0.990422
[425]	train-auc:0.992099	valid-auc:0.990598
[450]	train-auc:0.992202	valid-auc:0.990782
[475]	train-auc:0.992324	val

In [49]:
from operator import itemgetter

def create_feature_map(features):
    outfile = open('xgb.fmap', 'w')
    for i, feat in enumerate(features):
        outfile.write('{0}\t{1}\tq\n'.format(i, feat))
    outfile.close()

def get_importance(gbm, features):
    create_feature_map(features)
    importance = gbm.get_fscore(fmap='xgb.fmap')
    importance = sorted(importance.items(), key=itemgetter(1), reverse=True)
    return importance

print(get_importance(gbm, list(X_train.columns.values)))

[('cycle_norm', 2112), ('s14', 1865), ('s9', 1797), ('s12', 1387), ('s11', 1335), ('s7', 1215), ('s4', 1203), ('s15', 1195), ('s3', 1070), ('s21', 1057), ('s2', 987), ('s20', 843), ('s13', 764), ('s8', 691), ('setting1', 417), ('s17', 401), ('setting2', 250)]


##Results on Train Set

In [50]:
from sklearn.metrics import accuracy_score
# training metrics

d_trn = xgb.DMatrix(train_df[cols]) 
pred_train = gbm.predict(d_trn)
pred_train = np.where(pred_train > 0.5, 1, 0)
print('Accurracy: {}'.format(accuracy_score(train_df['label1'], pred_train)))

Accurracy: 0.9728079104260579


In [51]:
from sklearn.metrics import confusion_matrix, recall_score, precision_score

print('Confusion matrix\n- x-axis is true labels.\n- y-axis is predicted labels')
cm = confusion_matrix(train_df['label1'], pred_train)
cm

Confusion matrix
- x-axis is true labels.
- y-axis is predicted labels


array([[17335,   196],
       [  365,  2735]])

##Results on Test Set

In [52]:
d_test =xgb.DMatrix(test_df[cols])
pred_test = gbm.predict(d_test)
pred_test = np.where(pred_test > 0.5, 1, 0)
print('Accurracy: {}'.format(accuracy_score(test_df['label1'], pred_test)))

Accurracy: 0.9866371411117899


In [53]:
print('Confusion matrix\n- x-axis is true labels.\n- y-axis is predicted labels')
cm = confusion_matrix(test_df['label1'], pred_test)
cm

Confusion matrix
- x-axis is true labels.
- y-axis is predicted labels


array([[12709,    55],
       [  120,   212]])

In [54]:
# compute precision and recall
precision_test = precision_score(test_df['label1'], pred_test)
recall_test = recall_score(test_df['label1'], pred_test)
f1_test = 2 * (precision_test * recall_test) / (precision_test + recall_test)
print( 'Precision: ', precision_test, '\n', 'Recall: ', recall_test,'\n', 'F1-score:', f1_test )

Precision:  0.7940074906367042 
 Recall:  0.6385542168674698 
 F1-score: 0.7078464106844741


In [55]:
label_array_test_last = test_df.groupby('id')['label1'].nth(-1).values
label_array_test_last = label_array_test_last.reshape(label_array_test_last.shape[0],1).astype(np.float32)
label_array_test_last.shape

(100, 1)

In [56]:
seq_array_test_last = [test_df[test_df['id']==id][cols].values[-1] for id in test_df['id'].unique()]

seq_array_test_last = np.asarray(seq_array_test_last).astype(np.float32)
seq_array_test_last.shape

(100, 25)

In [57]:
d_test_last = xgb.DMatrix(seq_array_test_last)
d_test_last.feature_names = d_trn.feature_names
pred_test_last = gbm.predict(d_test_last)
pred_test_last = np.where(pred_test_last > 0.5, 1, 0)
acc = accuracy_score(label_array_test_last, pred_test_last)
print('Accurracy: {}'.format(acc))

Accurracy: 0.92


In [58]:
# make predictions and compute confusion matrix
print('Confusion matrix\n- x-axis is true labels.\n- y-axis is predicted labels')
cm = confusion_matrix(label_array_test_last, pred_test_last)
cm

Confusion matrix
- x-axis is true labels.
- y-axis is predicted labels


array([[74,  1],
       [ 7, 18]])

In [59]:
# compute precision and recall
precision_test = precision_score(label_array_test_last, pred_test_last)
recall_test = recall_score(label_array_test_last, pred_test_last)
f1_test = 2 * (precision_test * recall_test) / (precision_test + recall_test)
print( 'Precision: ', precision_test, '\n', 'Recall: ', recall_test,'\n', 'F1-score:', f1_test )

Precision:  0.9473684210526315 
 Recall:  0.72 
 F1-score: 0.8181818181818181


##Summary of Results on Test Set

In [60]:
results_df = pd.DataFrame([[acc,precision_test,recall_test,f1_test],
                          ],
                         columns = ['Accuracy', 'Precision', 'Recall', 'F1-score'],
                         index = ['XGBoost'])
results_df

Accuracy  Precision  Recall  F1-score
XGBoost      0.92   0.947368    0.72  0.818182

#LSTM

In [0]:
# window size
sequence_length = 50

In [0]:
def gen_sequence(id_df, seq_length, seq_cols):
    """ Only sequences that meet the window-length are considered, no padding is used. This means for testing
    we need to drop those which are below the window-length. An alternative would be to pad sequences so that
    we can use shorter ones """
    data_array = id_df[seq_cols].values
    num_elements = data_array.shape[0]
    for start, stop in zip(range(0, num_elements-seq_length), range(seq_length, num_elements)):
        yield data_array[start:stop, :]

In [0]:
sensor_cols = ['s' + str(i) for i in range(1,22)]
sequence_cols = ['setting1', 'setting2', 'setting3', 'cycle_norm']
sequence_cols.extend(sensor_cols)

In [0]:
seq_gen = (list(gen_sequence(train_df[train_df['id']==id], sequence_length, sequence_cols)) 
           for id in train_df['id'].unique())

In [68]:
seq_array = np.concatenate(list(seq_gen)).astype(np.float32)
seq_array.shape

(15631, 50, 25)

In [0]:
def gen_labels(id_df, seq_length, label):
    data_array = id_df[label].values
    num_elements = data_array.shape[0]
    return data_array[seq_length:num_elements, :]

In [70]:
label_gen = [gen_labels(train_df[train_df['id']==id], sequence_length, ['label1']) 
             for id in train_df['id'].unique()]
label_array = np.concatenate(label_gen).astype(np.float32)
label_array.shape

(15631, 1)

##Model

In [71]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM, Activation

Using TensorFlow backend.


In [72]:
nb_features = seq_array.shape[2]
nb_out = label_array.shape[1]

model = Sequential()
model.add(LSTM(input_shape=(sequence_length, nb_features), units=100, return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(units=100, return_sequences=False))
model.add(Dropout(0.2))
model.add(Dense(units=nb_out, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

W0702 01:32:01.469855 139990583084928 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0702 01:32:01.515223 139990583084928 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0702 01:32:01.523682 139990583084928 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0702 01:32:01.803738 139990583084928 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

W0702 01:32:01.815823 

In [73]:
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 50, 100)           50400     
_________________________________________________________________
dropout_1 (Dropout)          (None, 50, 100)           0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               80400     
_________________________________________________________________
dropout_2 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 130,901
Trainable params: 130,901
Non-trainable params: 0
_________________________________________________________________
None


##Training the Model

In [74]:
%%time
model.fit(seq_array, label_array, epochs=10, batch_size=200, validation_split=0.05, verbose=1,
          callbacks = [keras.callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=0, verbose=0, mode='auto')])

Train on 14849 samples, validate on 782 samples
Epoch 1/10
14849/14849 [==============================] - 30s 2ms/step - loss: 0.2268 - acc: 0.9075 - val_loss: 0.1494 - val_acc: 0.9348
Epoch 2/10
14849/14849 [==============================] - 28s 2ms/step - loss: 0.1023 - acc: 0.9584 - val_loss: 0.0824 - val_acc: 0.9591
Epoch 3/10
14849/14849 [==============================] - 28s 2ms/step - loss: 0.0831 - acc: 0.9665 - val_loss: 0.0607 - val_acc: 0.9757
Epoch 4/10
14849/14849 [==============================] - 28s 2ms/step - loss: 0.0735 - acc: 0.9689 - val_loss: 0.0470 - val_acc: 0.9834
Epoch 5/10
14849/14849 [==============================] - 28s 2ms/step - loss: 0.0682 - acc: 0.9709 - val_loss: 0.0983 - val_acc: 0.9540
CPU times: user 4min 10s, sys: 15.3 s, total: 4min 26s
Wall time: 2min 22s


##Results on Train Set

In [75]:
scores = model.evaluate(seq_array, label_array, verbose=1, batch_size=200)
print('Accurracy: {}'.format(scores[1]))

15631/15631 [==============================] - 7s 418us/step
Accurracy: 0.9612948644848369


In [76]:
y_pred = model.predict_classes(seq_array,verbose=1, batch_size=200)
y_true = label_array
print('Confusion matrix\n- x-axis is true labels.\n- y-axis is predicted labels')
cm = confusion_matrix(y_true, y_pred)
print (cm)

15631/15631 [==============================] - 7s 455us/step
Confusion matrix
- x-axis is true labels.
- y-axis is predicted labels
[[12501    30]
 [  575  2525]]


In [77]:
precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)
print( 'precision = ', precision, '\n', 'recall = ', recall)

precision =  0.9882583170254403 
 recall =  0.8145161290322581


##Results on Test Set

In [78]:
seq_array_test_last = [test_df[test_df['id']==id][sequence_cols].values[-sequence_length:] 
                       for id in test_df['id'].unique() if len(test_df[test_df['id']==id]) >= sequence_length]

seq_array_test_last = np.asarray(seq_array_test_last).astype(np.float32)
seq_array_test_last.shape

(93, 50, 25)

In [0]:
y_mask = [len(test_df[test_df['id']==id]) >= sequence_length for id in test_df['id'].unique()]

In [80]:
label_array_test_last = test_df.groupby('id')['label1'].nth(-1)[y_mask].values
label_array_test_last = label_array_test_last.reshape(label_array_test_last.shape[0],1).astype(np.float32)
label_array_test_last.shape

(93, 1)

In [81]:
print(seq_array_test_last.shape)
print(label_array_test_last.shape)

(93, 50, 25)
(93, 1)


In [82]:
scores_test = model.evaluate(seq_array_test_last, label_array_test_last, verbose=2)
print('Accurracy: {}'.format(scores_test[1]))

Accurracy: 0.9139784888554645


In [83]:
y_pred_test = model.predict_classes(seq_array_test_last)
y_true_test = label_array_test_last
print('Confusion matrix\n- x-axis is true labels.\n- y-axis is predicted labels')
cm = confusion_matrix(y_true_test, y_pred_test)
print (cm)

Confusion matrix
- x-axis is true labels.
- y-axis is predicted labels
[[68  0]
 [ 8 17]]


In [84]:
precision_test = precision_score(y_true_test, y_pred_test)
recall_test = recall_score(y_true_test, y_pred_test)
f1_test = 2 * (precision_test * recall_test) / (precision_test + recall_test)
print( 'Precision: ', precision_test, '\n', 'Recall: ', recall_test,'\n', 'F1-score:', f1_test )

Precision:  1.0 
 Recall:  0.68 
 F1-score: 0.8095238095238095


##Summary of Results on Test Set

In [85]:
results_df = pd.DataFrame([[scores_test[1],precision_test,recall_test,f1_test]],
                         columns = ['Accuracy', 'Precision', 'Recall', 'F1-score'],
                         index = ['LSTM'])
results_df

Accuracy  Precision  Recall  F1-score
LSTM  0.913978        1.0    0.68  0.809524